import Contexts from "../context"
import "./globals.css"
import "react-toastify/dist/ReactToastify.css"
import { Inter } from "next/font/google"
import { ToastContainer } from "react-toastify"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Lotus Cinema</title>
        <meta name="description" content="Lotus Cinema Movie Selector" />
        <meta charSet="UTF-8" />
      </head>

      <body className={inter.className}>
        <Contexts>{children}</Contexts>
      </body>
    </html>
  )
}
